plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "me.modmuss50.mod-publish-plugin" version "${mod_publish_version}"
}

base {
    archivesName = "${mod_name}-fabric-${minecraft_version}-${version_fabric}"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
// Use attribute for include-ed dependencies
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = project(":common").file("CHANGELOG.md").text
    type = STABLE
    modLoaders.add("fabric")
    displayName = "${mod_name}-fabric-${minecraft_version}-${version_fabric}"
    dryRun = dry_run.toBoolean()
    version = version_fabric

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = curseforge_project_id
        minecraftVersions.add(minecraft_version)
        optional("euphoria-patches")
    }


    modrinth {
        accessToken = accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = modrinth_project_id
        minecraftVersions.add(minecraft_version)
        optional("euphoria-patches")
    }

}