# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version_forge=1.2.15
version_fabric=1.0.3
version_neoforge=1.0.3
group=com.cozary.tintedcampfires
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Tinted Campfires
mod_author=Cozary
mod_id=tintedcampfires
license=All Rights Reserved
credits=Thanks for download this mod uwu
description=Add beautiful campfires to the game of each color to decorate!
minecraft_version_range=[1.21.11, 1.22)

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric https://fabricmc.net/develop/
fabric_version=0.140.0+1.21.11
fabric_loader_version=0.18.3

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=61.0.2
forge_loader_version_range=[61,)

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.11.12-beta
neoforge_loader_version_range=[4,)

# Publishing
mod_publish_version=0.8.4
dry_run=false
curseforge_project_id=479516
modrinth_project_id=M7fxJvf2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
