plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '7.0.25'
    id "me.modmuss50.mod-publish-plugin" version "${mod_publish_version}"
    id 'idea'
}

base {
    archivesName = "${mod_name}-forge-${minecraft_version}-${version_forge}"
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    // Automatically enable forge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer.from(at)
    }

    runs {
        client {
            workingDir = file('runs/client')
        }

        server {
            workingDir = file('runs/server')
        }

        data {
            workingDir = file('runs/data')
            args.addAll('--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath())
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = getLatestChangelog()
    type = STABLE
    modLoaders.add("forge")
    displayName = "${mod_name}-forge-${minecraft_version}-${version_forge}"
    dryRun = dry_run.toBoolean()
    version = version_forge

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = curseforge_project_id
        minecraftVersions.add(minecraft_version)
        client = true
        server = true
        optional("euphoria-patches")
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = modrinth_project_id
        minecraftVersions.add(minecraft_version)
        optional("euphoria-patches")
    }
}
