plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "me.modmuss50.mod-publish-plugin" version "${mod_publish_version}"
}

base {
    archivesName = "${mod_name}-neoforge-${minecraft_version}-${version_neoforge}"
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file('runs/data'))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file('runs/server').createParentDirectories()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = getLatestChangelog()
    type = STABLE
    modLoaders.add("neoforge")
    displayName = "${mod_name}-neoforge-${minecraft_version}-${version_neoforge}"
    dryRun = dry_run.toBoolean()
    version = version_neoforge

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = curseforge_project_id
        minecraftVersions.add(minecraft_version)
        client = true
        server = true
        optional("euphoria-patches")
    }


    modrinth {
        accessToken = accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = modrinth_project_id
        minecraftVersions.add(minecraft_version)
        optional("euphoria-patches")
    }

}

// Task to move generated resources to common module
tasks.register('moveGeneratedResources', Copy) {
    group = mod_id
    description = "Moves generated resources to common module, overwriting duplicates."
    from 'src/generated/resources'
    into rootProject.project(':common').file('src/main/resources')
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    doLast {
        file('src/generated/resources').deleteDir()
    }
}

// Automatically run moveGeneratedResources after runData (Only works when running the Gradle task, not the IDE Run Config)
tasks.named('runData') {
    finalizedBy 'moveGeneratedResources'
}